using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Dosnic.Tests.Unit
{
    [TestClass]
    public class CryptoTests
    {
        private Crypto<string> _crypto;

        [TestInitialize]
        public void Setup()
        {
            _crypto = CryptoUtils.Initialize<string>().WithAutoGeneratedKeyAndIV();
        }

        [TestCleanup]
        public void CleanUP()
        {
            _crypto.Dispose();
        }

        [TestMethod]
        public void Should_encrypt_object()
        {
            var encryptedOject = _crypto.Encrypt("ohh hai");

            encryptedOject.Should().NotBeNullOrEmpty();
        }

        [TestMethod]
        public void Should_encrypt_and_decrypt_object()
        {
            var encryptedOject = _crypto.Encrypt("ohh hai");
            var decryptedObject = _crypto.Decrypt(encryptedOject);

            decryptedObject.Should().BeEquivalentTo("ohh hai");
        }

        [TestMethod]
        public void Should_ctor_with_default_json_serializer()
        {
            _crypto.JsonSerializer.Should().BeOfType<Utils.JsonSerializer>();
            _crypto.JsonSerializer.Should().NotBeNull();
        }
    }
}
