using System;
using System.Security.Cryptography;

namespace Dosnic
{
    public static class CryptoUtils
    {
        public static Crypto<T> Initialize<T>(SymmetricAlgorithm symetricAlgorithm = null)
            where T: class
        {
            var crypto = new Crypto<T>()
            {
                Key = null,
                IV = null,
                SymetricAlgo = symetricAlgorithm ?? new RijndaelManaged()
            };

            return crypto;
        }

        public static Crypto<T> WithAutoGeneratedKeyAndIV<T>(this Crypto<T> crypto)
            where T : class
        {
            crypto.GenerateSecretKey();
            crypto.GenerateSecretIV();
            return crypto;
        }

        public static Crypto<T> WithKey<T>(this Crypto<T> crypto, string key)
            where T : class
        {
            crypto.Key = key;
            return crypto;
        }

        public static Crypto<T> WithIV<T>(this Crypto<T> crypto, string iv)
            where T : class
        {
            crypto.IV = iv;
            return crypto;
        }

        public static Crypto<T> GenerateSecretKey<T>(this Crypto<T> crypto, int keySize = 256)
        {
            crypto.SymetricAlgo.KeySize = keySize;
            crypto.SymetricAlgo.GenerateKey();
            crypto.Key = Convert.ToBase64String(crypto.SymetricAlgo.Key);

            return crypto;
        }

        public static Crypto<T> GenerateSecretIV<T>(this Crypto<T> crypto)
        {
            crypto.SymetricAlgo.GenerateIV();
            crypto.IV = Convert.ToBase64String(crypto.SymetricAlgo.IV);

            return crypto;
        }
    }
}
