using System;
using System.Security.Cryptography;

namespace Dosnic
{
    public static class CryptoUtils
    {
        public static Crypto Initialize(SymmetricAlgorithm symetricAlgorithm = null)
        {
            var crypto = new Crypto()
            {
                Key = null,
                IV = null,
                SymetricAlgo = symetricAlgorithm ?? new RijndaelManaged()
            };

            return crypto;
        }

        public static Crypto WithAutoGeneratedKeyAndIV(this Crypto crypto)
        {
            crypto.GenerateSecretKey();
            crypto.GenerateSecretIV();
            return crypto;
        }

        public static Crypto WithKey(this Crypto crypto, string key)
        {
            crypto.Key = key;
            return crypto;
        }

        public static Crypto WithIV(this Crypto crypto, string iv)
        {
            crypto.IV = iv;
            return crypto;
        }

        public static Crypto GenerateSecretKey(this Crypto crypto, int keySize = 256)
        {
            crypto.SymetricAlgo.KeySize = keySize;
            crypto.SymetricAlgo.GenerateKey();
            crypto.Key = Convert.ToBase64String(crypto.SymetricAlgo.Key);

            return crypto;
        }

        public static Crypto GenerateSecretIV(this Crypto crypto)
        {
            crypto.SymetricAlgo.GenerateIV();
            crypto.IV = Convert.ToBase64String(crypto.SymetricAlgo.IV);

            return crypto;
        }
    }
}
